### ISSUE TITLE
How to specify url port?

### ISSUE THREAD

**Issue by jveres** [eidam/cf-workers-status-page#11]
Is port specification in the config `url` expected to work?
Like `url: 'https://www.whatever.com:10001/'`.
I can't get this to work. Thx.

**Comment by eidam** [comment]
Thanks for reporting! That's a use-case I didn't try yet, gonna take a look later today.

**Comment by eidam** [comment]
@jveres I checked the URL from your config and I am also getting 525 (SSL handshake) errors from the Workers. It seems to be a known limitation, as described here https://community.cloudflare.com/t/fetch-in-worker-strips-port-number-from-url/189481

**Comment by jveres** [comment]
Yep, I too found the list of enabled ports in the CF firewall but those don't work in my case. Thanks for checking this out anyway.
