### ISSUE TITLE
Cloudflare free tier limits issues.

### ISSUE THREAD

**Issue by hibenji** [eidam/cf-workers-status-page#129]
I have been using this status page for a few months now. (thanks btw ❤️ )

Cloudflare sends out a 50% limit email every day, which is normal.
But today for the first time ever it sent me a 90% email.
I have not changed anything in the last 2-3 months, so im not sure what caused this.
Also i asked a friend that also uses this project, he seems to have gotten the same email/issue.
If what is happening continues, i will most likely hit the 100% limit in about an hour so.
I attached some photos.

![image](https://user-images.githubusercontent.com/65447501/232235551-2e2103c6-d790-491a-b0a2-1ee4ee781995.png)
![image](https://user-images.githubusercontent.com/65447501/232235565-5b4f3178-7728-493d-a3f3-f51663557f76.png)
![image](https://user-images.githubusercontent.com/65447501/232235593-06ddac20-3105-4162-9110-653929c5aedb.png)

Ill keep this thread updated if something else happens.

**Comment by eidam** [comment]
Hey, thanks for using it!

What cron trigger schedule do you have set up? Can you check your workers
dashboard to see past cron trigger schedules, do they seem normal -
following the schedule you have set?

**Comment by hibenji** [comment]
The default 2 minute, that should be enough for the free tier and has been working for the last couple of months.
The events seem fine to me, but i dont see that long of a history unfortunately.
I mean the same thing happened to my friend as well and we both havent touch it in a while.
![image](https://user-images.githubusercontent.com/65447501/232237043-06517f9c-c342-465e-8ffa-827c51fb39a4.png)
![image](https://user-images.githubusercontent.com/65447501/232236792-0b661667-44e6-4efc-b3ff-d606d0469d12.png)

**Comment by eidam** [comment]
Thanks for the info - just to confirm, you don’t have any other Workers
scripts in your account, right?

**Comment by hibenji** [comment]
Nope, thats all i use it for, and i havent touched cloudflare at all in a few weeks.
![image](https://user-images.githubusercontent.com/65447501/232237326-9d84ecf9-ddc9-436d-8461-21b7475d8a82.png)
![image](https://user-images.githubusercontent.com/65447501/232237334-d6b22032-c445-4f93-a17e-03b97780cbff.png)

**Comment by hibenji** [comment]
I have now reached the limit.
![image](https://user-images.githubusercontent.com/65447501/232239046-d7584988-9560-4a97-8b11-31758ce25454.png)

**Comment by 112RG** [comment]
Yep I have the same issue it just happens out of nowhere every couple of months

**Comment by hibenji** [comment]
> 

So it has happened before?

**Comment by gianklug** [comment]
I just got the **Daily request limit exceeded** Mail from Cloudflare, same situation as @hibenji

**Comment by supunsathsara** [comment]
Got the same email, saying 
`You are 50% of the way to reaching one of your daily Cloudflare Workers KV free tier limits.`
my cron triggers are set to 5 minutes.
it's the first time I got this email.

**Comment by elithrar** [comment]
(I’m from Cloudflare)

Can folks who are observing this include their Cloudflare account ID and KV namespace ID - ?

**Comment by rts-rob** [comment]
EM for KV - looking at this now. Echo @elithrar comments above - please share account and namespace ID.

**Comment by hibenji** [comment]
Here is my ids @elithrar:

Account id= `71571c8606d2bb2c159c3a610b341bda`
I think these are the namespace ids:
`87bd98f1d14d44ccafc5f0d8d455165a`
`c9ef7bc233314704b08f8304750a628d`
![image](https://user-images.githubusercontent.com/65447501/232314263-0d4587a2-26e6-4348-9ad1-528bfa8ef4ad.png)

**Comment by hibenji** [comment]
![image](https://user-images.githubusercontent.com/65447501/232314506-c94b78e0-fd16-4956-b3c4-bfe877cc2c67.png)
I havent gotten the 90% email today yet, but considering that the 50% email came at about 10am today like it did yesterday, im guessing the issue still exists.
Usually it comes at around 6pm.

**Comment by rts-rob** [comment]
Monitoring the fix, which appears to be working: https://www.cloudflarestatus.com/incidents/fxhsgv1myxzg

**Comment by hibenji** [comment]
Yep, seems to be working 👍 
I was at 1.43k, i am now at 1.38k
![image](https://user-images.githubusercontent.com/65447501/232320099-d9306b43-697d-4582-97e2-1101a00b5ec6.png)

Thanks for your help :)

**Comment by saewitz** [comment]
@rts-rob This just happened to us. We got 50% emails every day for a few weeks, and today got a 90% email.

**Comment by rts-rob** [comment]
Hi @saewitz - thanks for letting us know. This issue is closed; can you please cut a new one or [join us in our Discord server](https://discord.gg/cloudflaredev) to discuss?

Please include your Cloudflare account ID and KV namespace ID - both of these values are safe to post publicly.
