### ISSUE TITLE
Deploy failing after several components updates

### ISSUE THREAD

**Issue by symisc** [eidam/cf-workers-status-page#24]
Starting from yesterday, deploy is failing with the attached error message. We are suspecting _flareact_ breaking something somewhere:

![Screenshot_2020-12-15 Build software better, together(1)](https://user-images.githubusercontent.com/4615920/102268248-5ce35000-3f1b-11eb-8bb1-928e412bf601.png)

![Screenshot_2020-12-15 Build software better, together](https://user-images.githubusercontent.com/4615920/102267667-8c458d00-3f1a-11eb-8da9-28e6136e00fb.png)

**Comment by eidam** [comment]
I just checked your pipeline and it seems your build stage failed to build the project (the fact its not failing after error is different question)

@symisc could you please check the spacing in your config file? seems like they are off starting here https://github.com/symisc/cf-workers-status-page/blob/main/config.yaml#L34

```
yarn run v1.22.5
$ yarn css && flareact build
$ postcss public/tailwind.css -o public/style.css
Building your Flareact project for production...
[publish] 
[publish] ERROR in ./config.yaml
[publish] Module build failed (from ./node_modules/yaml-loader/index.js):
[publish] YAMLSyntaxError: All collection items must start at the same column at line 1, column 1:
[publish] 
[publish] settings:
[publish] ^^^^^^^^^...
```

**Comment by symisc** [comment]
My bad! Devops are exhausted on this period of the year :) Anyway! Thanks for your assistance
