### ISSUE TITLE
__STATIC_CONTENT_MANIFEST is not defined error when deploying components manually

### ISSUE THREAD

**Issue by dgdevops** [eidam/cf-workers-status-page#26]
Hi,

I have just deployed the status page using my GitHub pipeline.
In order to deploy it with my own pipeline with terraform my idea was to check all the components (script, NS, KV, bindings, triggers) of the newly deployed status page and try to deploy these parts using terraform. I managed to create the worker, namespaces, bindings however when I open the status page none of the .js or .css files load on the site.
Upon opening these assets I can see "`__STATIC_CONTENT_MANIFEST is not defined`" error on the site.
Based on the name in the error message I suppose I was missing a variable binding so I created a new with variable __STATIC_CONTENT_MANIFEST pointing to the __cf-workers-status-page-production-workers_sites_assets namespace despite the fact that the wrangler deployed worker does not have that variable binding. After that I stumbled upon the following error (example): "[could not find logo-192x192.png in your content namespace](url)".

In my terraform manifest I create 2x namespaces, 2x bindings, 1x script [copied from the original worker], 1x trigger [every 2 mins], file uploads [1 file to cf-workers-status-page-KV_STATUS_PAGE namespace & 12 files to __cf-workers-status-page-production-workers_sites_assets namespace].

Is there any component in the worker's setup that cannot be deployed manually that could cause such error?

Thanks.
D.

**Comment by eidam** [comment]
Hello, 

the `__STATIC_CONTENT_MANIFEST` is related to the Workers site, once the project is built to the static folder Wrangler takes its content and upload it there. Its related to this part of the config https://github.com/eidam/cf-workers-status-page/blob/main/wrangler.toml#L10-L12

Could you share how are you building the site and uploading it to the Workers via Terraform?

**Comment by dgdevops** [comment]
Hello @eidam,
I managed to fix the issue in the meantime.
I had to add ` __STATIC_CONTENT_MANIFEST` KV Namespace Bindings manually to the worker.
Additionally, I had to adjust the .js and .css file names to match the script's code.

Regards,
D.

**Comment by eidam** [comment]
Glad to see that, nice! :) 

Have a great day!
Eidam
