### ISSUE TITLE
Possibility to check the websites from a static location

### ISSUE THREAD

**Issue by dgdevops** [eidam/cf-workers-status-page#27]
Hello @eidam,

I successfully deployed the status-page to my Cloudflare workers and the status checks are executed according to the cron trigger.
After deploying the status-page I realized that on the website I am monitoring geoblock is enabled so it can be viewed only from certain locations, meaning that the status check fails in case the code is executed on a worker that is located in a restricted country. According to the current Cloudflare capabilities the code cannot be executed from a specific Cloudflare location all the time and preferably I would like to avoid whitelisting the Cloudflare IP ranges.

Is there any way to kind of replace/spoof the original location of the worker (in code) with a static one to avoid the block?

Thanks,
D.

**Comment by eidam** [comment]
Hello @dgdevops, 

unfortunately, there is no way to control where the CRON Triggers is scheduled and run (as Cloudflare is scheduling them to least used datacenters at a given time) and I don't think there is a way to spoof the location either :) 

Eidam

**Comment by dgdevops** [comment]
Hello @eidam,

Based on my research I found the same.
Thanks for checking,

Cheers
