### ISSUE TITLE
Confusion on "Not all systems operational"

### ISSUE THREAD

**Issue by ramithuh** [eidam/cf-workers-status-page#28]
Hi !

I deployed the status page [https://status.rotaract.social](https://status.rotaract.social). I'm not sure why "Not all systems operational" is displayed for each day 🤔(even though everything looks ok) 

Any suggestions would be greatly appreciated!

**Comment by eidam** [comment]
Hello @ramithuh, seems there are a couple of monitors in your state that were not operational and didn't get cleaned up correctly once you removed them from your config. 
For example `rotaractmora-manusath-contrib-portal`

What version of the Status Page are you using? Some garbage collection was refactored in the latest version (https://github.com/eidam/cf-workers-status-page/releases/tag/v1.2.0)

**Comment by ramithuh** [comment]
I'm using the latest version 😃,
I just edited the lastUpdate's **all operational** to true.. wonder why these two entries don't have detailed info
<img width="310" alt="image" src="https://user-images.githubusercontent.com/3503098/105815867-893dc200-5fd9-11eb-8668-15439a14a9e7.png">

**Comment by eidam** [comment]
One thing to note, KV takes a while to propagate to all datacenters, so your change might have been overwritten by the CRON before it reached the dc it's running in

**Comment by eidam** [comment]
You also need to specify the URL that returns the expected code or set `followRedirect` to true. 

It's by default disabled as redirect counts toward fetch() limit in Workers (50)

**Comment by ramithuh** [comment]
Thank You for your help!,
I tried editing the two fields and now it seems to work..  [https://status.rotaract.social](https://status.rotaract.social)
<img width="344" alt="image" src="https://user-images.githubusercontent.com/3503098/105819335-0d924400-5fde-11eb-8372-fa7dfcee3082.png">

**Comment by eidam** [comment]
Nice! Glad it works now! :) I will take a look into the GC script, so the first issue will be eliminated automatically :)
