### ISSUE TITLE
optimize KV operations in favor of KV free tier

### ISSUE THREAD

**Issue by eidam** [eidam/cf-workers-status-page#4]
- run monitors gc after deployment
  - currently runs on each scheduled event - this can be handled by `postCommands`  after deployment
- cache rendered frontend for longer and invalidate cache on changes from CRONs

- document how to change CRON trigger schedule to fit into free tier

**Comment by adaptive** [comment]
I read the code, and it looks the there is a possibility to reduce cost (of at least resources).
I have built my own monitor solution w/ Triggers and was considering ditching my monitor in favour of this project.

What is your expected timeframe for this implementation?

**Comment by eidam** [comment]
@adaptive I did prepare [this](https://github.com/eidam/cf-workers-status-page/pull/13) yesterday, which I plan to merge later today. 

I will be looking into some more optimizations over the weekend - specifically into using KV values of the monitor keys to store failed days instead of writing them as separate keys.

Do you have any other ideas to save some more resources?

**Comment by adaptive** [comment]
With KV value at the 25Mb limit, you can store history in just one key(failed days), config data I store on the Environment Variables.

**Comment by eidam** [comment]
thank you for the input, I will look into it

**Comment by eidam** [comment]
@adaptive its refactored, now it takes only 1 read + 1 write per scheduled run

**Comment by adaptive** [comment]
Great, I will read the code.
