### ISSUE TITLE
Worker threw exception

### ISSUE THREAD

**Issue by gd1214b** [eidam/cf-workers-status-page#48]
https://user-images.githubusercontent.com/37929478/121793940-8bc25080-cc36-11eb-9c14-7b058be65dc5.mp4

**Comment by eidam** [comment]
This seems to be an issue with deploy Workers workflow itself, gonna forward it to Workers Discord

**Comment by W4JEW** [comment]
@eidam did you ever hear anything back on this? I just tried deploying and also received the same "Error 1101".

I did try to deploy another GitHub project (https://github.com/cloudflare/workers-graphql-server) and that did work as expected.

Maybe you could DM me? I might know someone at Cloudflare that can help. ;-)

**Comment by SoftCreatR** [comment]
Same here.
