### ISSUE TITLE
Domain keeps 'not operational'

### ISSUE THREAD

**Issue by hazcod** [eidam/cf-workers-status-page#72]
Hi, thank you for your work!

I am running https://status.iron.security from a fork at https://github.com/iron-security/status .
As you can see, api.iron.security was marked for an incident on the 16th of November, but it's still showing as 'not operational' even tough it works currently.

Any idea why?

**Comment by 5u9** [comment]
change `false` to `true` config.yaml :eyes:

```yaml
followRedirect: true # should fetch follow redirects, default=false
```

**Comment by hazcod** [comment]
That seems to do the trick, thanks!
