### ISSUE TITLE
Not updating?

### ISSUE THREAD

**Issue by MyNameIsTito** [eidam/cf-workers-status-page#78]
Hi team I followed through the details on the read me but I don't believe its updating on my workers page.

Any help would be appreciated.

Git - https://github.com/MyNameIsTito/cf-workers-status-page
Workers Page - https://cf-workers-status-page-production.kzg.workers.dev/

**Comment by eidam** [comment]
Hey! I pushed a fix of your config here https://github.com/MyNameIsTito/cf-workers-status-page/pull/1

**Comment by MyNameIsTito** [comment]
why thank you!
